"""Entrypoint for the OpenAI test generator.

Usage in CI (triggered by a `/generate-tests` PR comment):
    python generate_tests.py

Usage locally (dry-run against a saved findings JSON):
    python generate_tests.py --findings-file /tmp/findings.json --dry-run

In CI mode this:
  1. Reads the PR number from the GitHub event payload.
  2. Finds the most recent AI QA Agent review comment on that PR.
  3. Extracts the structured findings JSON embedded in it.
  4. Calls OpenAI to generate one Kotlin test file per missing-test finding.
  5. Commits the new files on a branch `gen/tests-<PR>` and opens a follow-up PR.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

# Load .env if present (no-op in CI)
try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent / ".env")
except ImportError:
    pass

import requests

from tools.test_generator import generate_tests, write_tests
from tools.test_reviewer import extract_findings_from_comment


GITHUB_API = "https://api.github.com"
REPO_ROOT = Path(__file__).resolve().parent.parent


def _gh_headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _load_event() -> dict:
    path = os.environ.get("GITHUB_EVENT_PATH")
    if not path or not os.path.isfile(path):
        raise RuntimeError(
            "GITHUB_EVENT_PATH not set — generate_tests.py is meant to run "
            "inside a GitHub Actions workflow, or locally with --findings-file."
        )
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _resolve_pr_from_event(event: dict) -> tuple[str, int]:
    """Return (repo_full_name, pr_number) from either a pull_request or an
    issue_comment event (slash-command trigger)."""
    if event.get("pull_request"):
        return event["repository"]["full_name"], event["pull_request"]["number"]
    if event.get("issue") and event["issue"].get("pull_request"):
        return event["repository"]["full_name"], event["issue"]["number"]
    raise RuntimeError("Event payload has no PR context.")


def _find_findings_in_pr(repo: str, pr_number: int, token: str) -> dict:
    """Walk PR comments newest-first and return the first one with embedded findings."""
    url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments?per_page=100"
    resp = requests.get(url, headers=_gh_headers(token), timeout=30)
    resp.raise_for_status()
    comments = resp.json()
    for c in reversed(comments):
        body = c.get("body", "") or ""
        findings = extract_findings_from_comment(body)
        if findings:
            return findings
    raise RuntimeError(
        "No AI QA Agent comment with embedded findings found on this PR. "
        "Make sure the review workflow ran first."
    )


def _run(cmd: list[str], cwd: Path | None = None, env: dict | None = None) -> str:
    return subprocess.check_output(cmd, cwd=cwd, env=env, text=True).strip()


def _open_followup_pr(
    *,
    repo: str,
    pr_number: int,
    token: str,
    written: list[Path],
    findings: dict,
) -> str:
    """Commit the generated tests on a new branch and open a follow-up PR."""
    if not written:
        return ""

    branch = f"gen/tests-{pr_number}"
    bot_email = "actions@github.com"
    bot_name = "github-actions[bot]"

    # Configure git (CI runner has none by default)
    _run(["git", "config", "user.email", bot_email], cwd=REPO_ROOT)
    _run(["git", "config", "user.name", bot_name], cwd=REPO_ROOT)

    # Start from the head of the PR branch, not main, so the generated tests
    # land on top of the change being reviewed.
    pr_info = requests.get(
        f"{GITHUB_API}/repos/{repo}/pulls/{pr_number}",
        headers=_gh_headers(token),
        timeout=30,
    ).json()
    base_branch = pr_info["head"]["ref"]

    _run(["git", "fetch", "origin", base_branch], cwd=REPO_ROOT)
    _run(["git", "checkout", "-B", branch, f"origin/{base_branch}"], cwd=REPO_ROOT)

    for p in written:
        _run(["git", "add", str(p)], cwd=REPO_ROOT)

    title = f"Auto-generated tests for #{pr_number}"
    body_lines = [
        f"This PR adds AI-generated tests for the gaps flagged on #{pr_number}.",
        "",
        "Generated by `mobile-qa-agent/generate_tests.py` (OpenAI).",
        "",
        "**Files added:**",
        *[f"- `{p.relative_to(REPO_ROOT)}`" for p in written],
        "",
        "Please review each file — generated tests should still be sanity-checked.",
    ]
    body = "\n".join(body_lines)

    _run(["git", "commit", "-m", title], cwd=REPO_ROOT)

    # Push using the token in the URL (one-shot, not stored in config)
    push_url = f"https://x-access-token:{token}@github.com/{repo}.git"
    subprocess.check_call(
        ["git", "push", "-u", "--force-with-lease", push_url, branch],
        cwd=REPO_ROOT,
    )

    # Open PR
    pr_resp = requests.post(
        f"{GITHUB_API}/repos/{repo}/pulls",
        headers=_gh_headers(token),
        json={"title": title, "head": branch, "base": base_branch, "body": body},
        timeout=30,
    )
    if pr_resp.status_code >= 300:
        # Maybe a PR for this branch already exists
        existing = requests.get(
            f"{GITHUB_API}/repos/{repo}/pulls",
            headers=_gh_headers(token),
            params={"head": f"{repo.split('/')[0]}:{branch}", "state": "open"},
            timeout=30,
        ).json()
        if existing:
            return existing[0]["html_url"]
        pr_resp.raise_for_status()
    return pr_resp.json()["html_url"]


def _post_reply(repo: str, pr_number: int, token: str, body: str) -> None:
    requests.post(
        f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments",
        headers=_gh_headers(token),
        json={"body": body},
        timeout=30,
    ).raise_for_status()


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="OpenAI Kotlin test generator.")
    p.add_argument("--findings-file", help="Local JSON file with findings (skip GitHub).")
    p.add_argument("--dry-run", action="store_true", help="Don't write files or open PR.")
    p.add_argument("--max", type=int, default=5, help="Max tests to generate per run.")
    return p.parse_args()


def main() -> int:
    args = parse_args()

    # 1. Get the findings JSON
    if args.findings_file:
        findings = json.loads(Path(args.findings_file).read_text())
        repo = pr_number = None
    else:
        token = os.environ["GITHUB_TOKEN"]
        event = _load_event()
        repo, pr_number = _resolve_pr_from_event(event)
        findings = _find_findings_in_pr(repo, pr_number, token)

    # 2. Generate tests
    generated = generate_tests(findings, REPO_ROOT, max_targets=args.max)
    valid = [g for g in generated if g.is_valid]
    if not valid:
        print("No generatable findings — nothing to do.")
        if not args.dry_run and repo and pr_number:
            _post_reply(
                repo, pr_number, os.environ["GITHUB_TOKEN"],
                "🤖 `/generate-tests`: no actionable findings to generate from."
            )
        return 0

    # 3. Print or write
    if args.dry_run:
        for g in valid:
            print(f"\n----- {g.path} -----\n{g.code}\n")
        return 0

    written = write_tests(valid, REPO_ROOT, overwrite=False)
    print(f"Wrote {len(written)} test file(s).")

    # 4. If in CI, commit + open follow-up PR
    if repo and pr_number:
        token = os.environ["GITHUB_TOKEN"]
        url = _open_followup_pr(
            repo=repo, pr_number=pr_number, token=token,
            written=written, findings=findings,
        )
        if url:
            _post_reply(
                repo, pr_number, token,
                f"🤖 Generated {len(written)} test file(s) → {url}",
            )
            print(f"Follow-up PR: {url}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
